### ISSUE TITLE
Does this work with UINavigation Controller?

### ISSUE THREAD

**Issue by saulye** [robertmryan/SwiftCustomTransitions#1]
If one or both of the view controllers are embed in a UINavigationController, what steps must be taken to keep it working?

**Comment by robertmryan** [comment]
It depends. Are you overlaying the full screen? Or just part of the screen (e.g. keeping the navigation bar visible)?

**Comment by robertmryan** [comment]
If the source view controller is in navigation controller, rather than having first view controller's gesture recognizer do:

```swift
show(controller, sender: self)
```

you'd instead want it to explicitly `present`:

```swift
present(controller, animated: true)
```

Also, if you're supporting non-interactive presentation, too, you'd want to make the segue between the two be a modal presentation rather than just "showing", too.

**Comment by saulye** [comment]
Using present(controller, animated: true) works great! How though would I account for sceond viewcontroller being in its own navigation controller. I tried making the navigation controller have the identifier SecondViewController but that wont work because UINavigationController has no member customtransitiondelegate.

**Comment by robertmryan** [comment]
Two options: You can subclass `UINavigationController`, specify that as the base class for that scene in your storyboard, and put the `customTransitionDelegate` stuff there. Or you can use a standard  have the presenting view controller set the `transitioningDelegate` of the navigation controller itself, before it presents it.

**Comment by saulye** [comment]
Got it thanks !
